### ISSUE TITLE
text views are overlapping on fragment_tracking

### ISSUE THREAD

**Issue by sdcode001** [OpenLake/Sampoorna#21]
![Screenshot_20220301_165105](https://user-images.githubusercontent.com/92887905/156160948-5e76d58f-5d81-4875-ab73-7f070300e668.jpg)

i want to solve this issue

**Comment by sdcode001** [comment]
@ashutosh321607 i want to solve this issue. please assign it to me

**Comment by ashutosh321607** [comment]
> @ashutosh321607 i want to solve this issue. please assign it to me

@shashwatj07 @KShivendu

**Comment by aastha01chauhan** [comment]
Hi, thanks for your comments. We will soon have an onboarding meeting then you can start once the contribution period begins. @ashutosh321607 @sdcode001 Please wait for the announcements for Sampoorna in the discord channel itself.

**Comment by sdcode001** [comment]
@ashutosh321607 okay I'm waiting

**Comment by Nostalgia3102** [comment]
Hi everyone, I want to solve this issue. Please assign this task to me.
@ashutosh321607 @aastha01chauhan

**Comment by Himanshu1808** [comment]
I would like to work on this issue, can you please assign me? I am a GSSOC'22 participant.
Kindly assign me this issue.

**Comment by yellowHatpro** [comment]
Hi everyone, It's good to see your interest in the app. However, the issues are to be created by the mentors and the PAs only. Surely, we will consider your ideas, and for that reason, we have the discord channel active in GSSoC . For the issues that have been created up till now, we will have to close them.
