### ISSUE TITLE
Title: A feature to check the accurate bmi 

### ISSUE THREAD

**Issue by Vrushali-anil-Chaudhari** [OpenLake/Sampoorna#22]
We can implement a fragment where we can take information and give an accurate BMI of the user.

**Comment by sdcode001** [comment]
Hey @Vrushali-anil-Chaudhari I want to work on this issue. please assign me this issue.

**Comment by sdcode001** [comment]
@Vrushali-anil-Chaudhari I will try my best

**Comment by sdcode001** [comment]
Hello, @Vrushali-anil-Chaudhari @ashutosh321607 i want to work on this issue. please assign it to me.

**Comment by Nostalgia3102** [comment]
Yes @Vrushali-anil-Chaudhari, I am a beginner in this GSSOC'22, so please assign this task to me so that I can learn and complete this task.

Thanks!!

**Comment by IamRaja007** [comment]
![BMI 1](https://user-images.githubusercontent.com/71515810/156249680-855c68f1-c84d-491b-bc50-5a4d6122fd15.png)
![BMI 2](https://user-images.githubusercontent.com/71515810/156249686-6a321198-410d-4651-bde6-356d3d8c39d8.png)

@Vrushali-anil-Chaudhari I intend to implement these two screens for the required fragment.

Formula that should be used for calculating BMI -> Weight (in KGs) / (Height in metres)^2

Also, trying to get the data for age specific calculations too. I am researching on that presently. When found, I also intend to add a 'Age' field in the first screen.

Fonts and colors will be according to the ones used in the project.

Please review these screens, and provide your valuable input as to what changes are required further. 
Thanks!

**Comment by yellowHatpro** [comment]
Hi everyone, It's good to see your interest in the app. However, the issues are to be created by the mentors and the PAs only. Surely, we will consider your ideas, and for that reason, we have the discord channel active in GSSoC . For the issues that have been created up till now, we will have to close them.
