### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by logicgupta** [OpenLake/Sampoorna#23]
- Size in layout file are defined statically , it should be imported from dimen file
- Color to textview/ other views are defined statically , it should be imported from color xml file.

**Comment by logicgupta** [comment]
I would like to contribute

**Comment by Nostalgia3102** [comment]
I would also love to contribute ;-)

**Comment by yellowHatpro** [comment]
Hi everyone, It's good to see your interest in the app. However, the issues are to be created by the mentors and the PAs only. Surely, we will consider your ideas, and for that reason, we have the discord channel active in GSSoC . For the issues that have been created up till now , we will have to close them.
