### ISSUE TITLE
[Bug] The two text box of fragment_tracking.xml page overlaps with each other

### ISSUE THREAD

**Issue by Rupangkan** [OpenLake/Sampoorna#24]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the Bug.

The two TextViews date_text and subheading of the fragment_tracking.xml page overlaps with each other.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rupangkan** [comment]
![12ea6a3f-10f9-4b62-86d5-7235d1c8af0e](https://user-images.githubusercontent.com/64887274/156407194-851ed911-2204-41c4-9130-667d307a2ce7.jpg)

**Comment by Rupangkan** [comment]
Issues are going to be opened by Mentors and PA's only. They will assign issues soon.
Closing this issue as it is not created by the mentors and PA's.

**Comment by barkatul** [comment]
okay okay
