### ISSUE TITLE
Overlapping text in the Tracking Fragment

### ISSUE THREAD

**Issue by yellowHatpro** [OpenLake/Sampoorna#26]
- In the Tracking Fragment, the text showing number of days left shows overlapping text.
<br>

![image](https://user-images.githubusercontent.com/75999921/156488497-d5d23262-ac06-446f-84fc-55286881a053.png)

**Comment by Rupangkan** [comment]
@yellowHatpro Please assign this issue to me. I would like to work on this issue ASAP
