### ISSUE TITLE
Add Blogs Fragment

### ISSUE THREAD

**Issue by yellowHatpro** [OpenLake/Sampoorna#28]
- Add a Blogs Fragment, which is accessible by the bottom navigation currently available.
- Create a Recycler View inside it, which for now shows dummy text, and can be later used to get fetched results from some apis.

**Comment by ken1000minus7** [comment]
I would like to work on this issue ✌

**Comment by sdcode001** [comment]
@yellowHatpro  I want to work on this issue.

**Comment by MohitGupta121** [comment]
Can you please assign me this issue, I want to work on that @yellowHatpro

**Comment by AgarwalsRahul** [comment]
@yellowHatpro I would like to work on thi issue.

**Comment by Bhawna1203** [comment]
I want to work in this issue .Could you please assign it to me @yellowHatpro

**Comment by tanisha-bhadani** [comment]
@yellowHatpro I would like to work on this issue.Please assign it to me

**Comment by aastha01chauhan** [comment]
@ken1000minus7 are you working on this?

**Comment by MohitGupta121** [comment]
@aastha01chauhan  If he is not working can I'll work on that to implement Recycler view using API

**Comment by AgarwalsRahul** [comment]
I would like to work on this issue if he's not working.

**Comment by ken1000minus7** [comment]
@aastha01chauhan yup, a little busy with midsems in college so working a bit slowly 😅

**Comment by aastha01chauhan** [comment]
> @aastha01chauhan yup, a little busy with midsems in college so working a bit slowly 😅

sure

**Comment by AyushGupta649** [comment]
Can u assign me this issue
