### ISSUE TITLE
Declare All Static strings to string.xml

### ISSUE THREAD

**Issue by logicgupta** [OpenLake/Sampoorna#34]
I would like to work on this to optimize the code by following the best codding practices.

**Comment by barkatul** [comment]
I want to work on this. Can you please assign this to me

**Comment by logicgupta** [comment]
@yellowHatpro  I would like to work on this issue.

**Comment by AyushGupta649** [comment]
Can you please assign me this issue

**Comment by aastha01chauhan** [comment]
@logicgupta please go ahead

**Comment by logicgupta** [comment]
@[aastha01chauhan](https://github.com/aastha01chauhan) Plss check and merge
