### ISSUE TITLE
[Bug] In "Add Contact" page, pressing enter creates a new paragraph instead of jumping to the next section

### ISSUE THREAD

**Issue by its-me-debk007** [OpenLake/Sampoorna#39]
In the "Add Contact" page, on pressing enter user should be directed to the next text field instead of a new paragraph. Also, in the phone no. field, only numeric digits must be allowed to type.

**Comment by its-me-debk007** [comment]
Please assign me this under GSSOC 2022. I wanna work on this issue!

**Comment by yellowHatpro** [comment]
That's surely a bug. Thanks for pointing it out. You can work on this issue.

**Comment by yellowHatpro** [comment]
Issue solved.
