### ISSUE TITLE
Improve Edit Texts error visibility in Onboarding User Info Fragment

### ISSUE THREAD

**Issue by sarveshpatelsp** [OpenLake/Sampoorna#47]
I want to add some toast in onboarding_user_info.xml, and also want to change the font. Please raise my issue.
Also If anyone wants to contribute with me, please feel free to dm me in my Linkedin Profile. I am happy to work with you.

Regards, 
Sarvesh

**Comment by BudhirajaMadhav** [comment]
@aastha01chauhan what's your view on this? Do we need something like this?

**Comment by yellowHatpro** [comment]
Hello @sarveshpatelsp , yes you can work on this issue. Instead of a toast, I'd recommend using the material text fields set error feature.

**Comment by sarveshpatelsp** [comment]
@yellowHatpro Thanks for giving me this opportunity. I will give my best.

**Comment by yellowHatpro** [comment]
Hello @sarveshpatelsp are you still working on this issue?

**Comment by sarveshpatelsp** [comment]
Hello @yellowHatpro, Yes, I am still working on this. Sorry, for the delay, actually I am having my Mid Sem Tests and also have those assignments to complete. So I am too busy nowadays. Please, don't mind. I am also a newbie in this field. 
I hope you'll understand my problem. 
Thank You,

**Comment by yellowHatpro** [comment]
Hello @sarveshpatelsp , any update so far?
If you have any problems, you can discuss them on the channel.

**Comment by yellowHatpro** [comment]
Can anyone else work on this issue?

**Comment by ken1000minus7** [comment]
I can work on this issue. What exactly needs to be done? Adding toast sounds pretty vague 😅

**Comment by yellowHatpro** [comment]
Hello @ken1000minus7 , thanks for showing interest in the issue. Yeah, the name of the issue was not clear.
We have to use the Material Edit setError property for showing an error if the user skips any EditText field.
