### ISSUE TITLE
Add feature to add contacts from Phone's Contact app

### ISSUE THREAD

**Issue by yellowHatpro** [OpenLake/Sampoorna#54]
As of now, we need to manually add a contact to the contacts list.
Add a feature that let us choose a contact from the phone's contact app.
The person should still be able to manually enter contact.

**Comment by ken1000minus7** [comment]
I would like to work on this issue ✌️

**Comment by MohitGupta121** [comment]
@ken1000minus7 if you are not work on this issue can I'll?

**Comment by ken1000minus7** [comment]
Still working on it, taking a bit time to figure out how to properly show the contacts 😅

**Comment by MohitGupta121** [comment]
> Still working on it, taking a bit time to figure out how to properly show the contacts 😅

Okok no problem bro 😅
