### ISSUE TITLE
Debug the transition between fragments navigation using bottom navigation

### ISSUE THREAD

**Issue by yellowHatpro** [OpenLake/Sampoorna#55]
Issue:

https://user-images.githubusercontent.com/75999921/161398114-d16e9257-a312-4f38-baf8-d780facb9679.mp4

**Comment by MohitGupta121** [comment]
I want to work on this issue please assign me that @yellowHatpro

**Comment by MohitGupta121** [comment]
>  screen-20220403-004542.mp4

I have some douts that the issue is when user goto contact list and then he'll switch to another tab, you want he again come to main tab after click on 1st tab???
That's the issue??

**Comment by MohitGupta121** [comment]
Working bhaiya but not getting root cause.

**Comment by yellowHatpro** [comment]
Hi @MohitGupta121 , can you show a video preview of the change

**Comment by MohitGupta121** [comment]
No results in my changes it's same as last

**Comment by yellowHatpro** [comment]
What you can do is hide the bottom navbar when the contact list fragment appears for the time being.

**Comment by MohitGupta121** [comment]
> What you can do is hide the bottom navbar when the contact list fragment appears for the time being.

Okay, or will I change contact list fragment to activity??

**Comment by yellowHatpro** [comment]
Changing list fragment to activity won't be a good idea.
You can try to hide the bottom nav in this situation.

**Comment by MohitGupta121** [comment]
> Changing list fragment to activity won't be a good idea. You can try to hide the bottom nav in this situation.

Okay that's good, and when backpress then goto main fragment?

**Comment by yellowHatpro** [comment]
> 

yes

**Comment by MohitGupta121** [comment]
> Changing list fragment to activity won't be a good idea. You can try to hide the bottom nav in this situation.

@yellowHatpro can you please review PR #56 for this issue
