### ISSUE TITLE
PR Template

### ISSUE THREAD

**Issue by Chitrakshi2531** [OpenLake/Sampoorna#59]
Creating a pull request template to ensure that the pull request contains all the information and details regarding pr so that it will be easy to review them.

@yellowHatpro can you please assign me this ??

**Comment by yellowHatpro** [comment]
@Chitrakshi2531  Hello there. Sorry for the unavailability,  you can work on this issue.

**Comment by yellowHatpro** [comment]
Issue fixed by @Chitrakshi2531
